FROM ubuntu:24.04
ENV INSTALL_DIR=/opt/conjur-api-python
ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && \
  apt-get install -y bash \
                    binutils \
                    build-essential \
                    curl \
                    git \
                    jq \
                    libffi-dev \
                    libssl-dev \
                    libsqlite3-dev \
                    python3-dev \
                    gnome-keyring \
                    dbus-x11 \
                    zlib1g-dev

RUN mkdir -p $INSTALL_DIR
WORKDIR $INSTALL_DIR

# Install Python 3.14.x
ENV PYTHON_VERSION=3.14
ENV PYENV_ROOT="/root/.pyenv"
ENV PATH="$PYENV_ROOT/bin:$PYENV_ROOT/shims:$PATH"

RUN curl -L -s https://github.com/pyenv/pyenv-installer/raw/master/bin/pyenv-installer | bash \
    && eval "$(pyenv init --path)" \
    && env PYTHON_CONFIGURE_OPTS="--enable-shared" pyenv install $PYTHON_VERSION \
    && pyenv global $PYTHON_VERSION \
    && pip install wheel

# By putting this COPY command after we install Python, Docker will cache the Python installation layer,
# so that it doesn't have to be reinstalled every time we re-run during development and testing.
COPY ./requirements.txt $INSTALL_DIR/
RUN pip install -r requirements.txt

COPY . $INSTALL_DIR

# Create a truststore in the default OpenSSL dir
COPY ./ci/test/truststore.pem  /usr/lib/ssl/cert.pem
