#!/bin/bash -ex

COMPOSE_FILE_PATH="ci/test/conjur-deployment/docker-compose.yml"

docker_compose_command(){
  docker compose --file "$COMPOSE_FILE_PATH" --project-directory "${PWD}" "$@"
}
cleanup() {
  # docker_compose_command logs
  echo "Cleaning up..."
  docker_compose_command rm --stop --force
}

# trap 'cleanup' EXIT ERR

DEBUG="false"
function get_parameters() {
  while [[ $# -gt 0 ]]; do
    case $1 in
    -d | --debug)
      DEBUG="true"
      shift # past argument
      ;;
    *)
      echo "Unknown option $1"
      exit 1
      ;;
    esac
  done
}
get_parameters $@
cleanup

export REGISTRY_URL=${INFRAPOOL_REGISTRY_URL:-"docker.io"}

# Ensure we are in repo root
cd "$(git rev-parse --show-toplevel)"

echo "Building API container..."
docker_compose_command build test

docker_compose_command up -d jwt-server

if [ -z "$INFRAPOOL_TEST_CLOUD" ]; then
  echo "Generating certificate..."
  docker_compose_command up openssl

  echo "Starting Conjur..."
  docker_compose_command up -d conjur-https
  docker_compose_command exec -T conjur cp /oidc/certs/oidc-server.cert.pem /etc/ssl/certs/oidc-server.cert.pem
  docker compose --file "$COMPOSE_FILE_PATH" --project-directory "${PWD}" \
    exec -T conjur sh -c 'hash=$(openssl x509 -hash -in /etc/ssl/certs/oidc-server.cert.pem --noout) && ln -s /etc/ssl/certs/oidc-server.cert.pem /etc/ssl/certs/${hash}.0'
  docker_compose_command exec -T conjur conjurctl wait

  echo "Configuring Conjur..."
  admin_api_key=$(docker_compose_command exec -T conjur conjurctl role retrieve-key conjur:user:admin | tr -d '\r')
  export CONJUR_AUTHN_API_KEY=$admin_api_key
  export DEBUG=$DEBUG
  conjur_host_port=$(docker_compose_command port conjur 80)
  conjur_port="${conjur_host_port##*:}"
  export TEST_HOSTNAME=conjur-https

  echo "Starting test env..."
  docker_compose_command up -d test

  # Hint: '--privileged' is added here otherwise we will get operation
  # not permitted when attempting to do anything related to dbus
  if [[ "$DEBUG" == "true" ]]; then
    docker_compose_command exec test bash
    exit
  fi

  docker_compose_command run \
    --rm \
    --no-deps \
    test \
    bash -c "pytest -v -m 'integration' --junitxml=ci/test/output/pytest-integration-junit.xml"
else
  echo "Running Cloud tests..."

  echo "Starting test env..."
  docker_compose_command up -d test

  docker_compose_command run \
    --rm \
    --no-deps \
    -e "TEST_CLOUD=true" \
    -e "CONJUR_APPLIANCE_URL=$INFRAPOOL_CONJUR_APPLIANCE_URL" \
    -e "CONJUR_ACCOUNT=conjur" \
    -e "CONJUR_AUTHN_LOGIN=$INFRAPOOL_CONJUR_AUTHN_LOGIN" \
    -e "CONJUR_AUTHN_TOKEN=$(echo "$INFRAPOOL_CONJUR_AUTHN_TOKEN" | base64 --decode)" \
    -e "IDENTITY_TOKEN=$INFRAPOOL_IDENTITY_TOKEN" \
    test \
    bash -c "pytest -v -m 'integration and cloud' --junitxml=ci/test/output/pytest-cloud-junit.xml"
fi
