[pytest]
testpaths = tests
addopts = --strict-markers -s --cov=conjur_api --cov-report=xml --junitxml=ci/test/output/pytest-junit.xml
python_files = test_*.py
python_classes = *Test
python_functions = test_*
markers =
    unit: mark a test as a unit test.
    integration: mark a test as an integration test.
    cloud: represents a test that can be run against Conjur Cloud as well as Conjur OSS.
