#!/bin/bash -e

REQUIRED_VARS=( "TWINE_USERNAME"
                "TWINE_PASSWORD" )

# Sanity check
for required_var in "${REQUIRED_VARS[@]}"; do
  if [[ "${!required_var}" == "" ]]; then
    echo "ERROR: '$required_var' not set!"
    exit 1
  fi
done

TWINE_REPOSITORY_URL="https://upload.pypi.org/legacy/"

./ci/publish/update_package_version "$1"
./ci/publish/build_publish_container

echo "Publishing to PyPI..."
rm -rf ./dist/
docker run --rm \
           -t \
           -e TWINE_REPOSITORY_URL \
           -e TWINE_USERNAME \
           -e TWINE_PASSWORD \
           conjur-api-python3-publish bash -exc "
               echo 'Installing new versions of pip and wheel...'
               /usr/bin/env pip3 install --upgrade pip wheel

               echo 'Building distributable package...'
               /usr/bin/env python3 -m build

               echo 'Testing artifacts in dist/*'
               /usr/bin/env twine check dist/*

               echo 'Publishing package to '\$TWINE_REPOSITORY_URL' using account '\$TWINE_USERNAME'...'
               /usr/bin/env twine upload --skip-existing --repository-url $TWINE_REPOSITORY_URL dist/*
           "
