#!/bin/bash -e

cd "$(dirname "$0")"

main() {
  if [ -z "$1" ]; then
    echo "No version argument supplied"
    exit 1
  else
    version="$1"
    echo "Updating module to version $version"
    update_version "../../conjur_api/__init__.py" "s/__version__ =.+/__version__ = \"$version\"/"
  fi
}

update_version() {
	local path="$1"
	local sed_expr="$2"

	if ! sed -E -i "" -e "$sed_expr" "$path" ; then
		echo "sed error $?" >&2
		exit 1
	fi
}

main "$@"
