#!/bin/bash -e

main() {
  if [ -z "$1" ]; then
    echo "No version argument supplied"
    exit 1
  else
    version="$1"
    echo "Updating module to version $version"
    update_version "./conjur_api/__init__.py" "s/__version__ =.+/__version__ = \"$version\"/"
  fi
}

update_version() {
	local path="$1"
	local sed_expr="$2"

  if [[ "$OSTYPE" == "darwin"* ]]; then
    sed -E -i "" -e "$sed_expr" "$path"
  else
    sed -E -i -e "$sed_expr" "$path"
  fi
}

main "$@"
